remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
color_scheme: pidark
nav_sort: case_sensitive
title: My first Docs
author: Ice Climber
email: docs@ladataweb.com
description: > # this means to ignore newlines until "baseurl:"
  This is the description of the Github Lab project for Github Page :)
  Stay tuned to know more about this Lab.

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
# github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

# show_excerpts: true # set to false to remove excerpts on the homepage
